# Starter pipeline
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: FortifySCA@7
- task: FortifySCA@7
  inputs:
    runBuildTranslate: true
    applicationType: 'dotnet'
    fortifyProjects: '**\*.sln'
    fortifyBuildId: '20201224'
    runFortifyRulepackUpdate: false
    runFortifyClean: true
    scaVerbose: false
    scaDebug: false
    runFortifyScan: true
    fortifyScanType: 'Local'
  inputs:
    runBuildTranslate: true
    applicationType: 'dotnet'
    fortifyProjects: '**\*.sln'
    fortifyBuildId: '20201224'
    runFortifyRulepackUpdate: false
    runFortifyClean: true
    scaVerbose: false
    scaDebug: false
    runFortifyScan: true
    fortifyScanType: 'Local'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
